apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sre-agent.fullname" . }}-config
  labels:
    {{- include "sre-agent.labels" . | nindent 4 }}
type: Opaque
data:
  config.toml: {{ .Values.codexConfig | b64enc | quote }}
  config: {{ .Values.kubeConfig | b64enc | quote }}
